<?php
	if(isset($_SESSION['mdd']))
	{
		// $con=mysqli_connect('localhost',$_SESSION['mdd']['uname'],$_SESSION['mdd']['pass'],'blinkcoders_mdd');
		$con=mysqli_connect('localhost',$_SESSION['mdd']['uname'],$_SESSION['mdd']['pass'],'mdd');
		if($con)
		{
		}
		else
		{
			session_destroy($_SESSION['mdd']);
			header('Location:index.php');
		}
	}
	else
	{
		header('Location:logout.php');
	}
?>